Update regressions.yml

diff --git a/.github/workflows/regressions.yml b/.github/workflows/regressions.yml
--- a/.github/workflows/regressions.yml
+++ b/.github/workflows/regressions.yml
@@ -14,7 +14,7 @@ jobs:
     steps:   
       - name: Validate network option
         id: network-check
-        run: (echo "beta dev grpc magma stream test" | grep -w "${{ github.event.inputs.network }}" > /dev/null && echo '::set-output name=VALID_NETWORK::true') || echo '::set-output name=VALID_NETWORK::false' && echo "INVALID NETWORK [${{ github.event.inputs.network }}] SUPPLIED" && exit 1
+        run: (echo "beta dev grpc magma stream test" | grep -w "${{ github.event.inputs.network }}" > /dev/null && echo '::set-output name=VALID_NETWORK::true') || (echo '::set-output name=VALID_NETWORK::false' && echo "INVALID NETWORK [${{ github.event.inputs.network }}] SUPPLIED" && exit 1)
    
       - name: checkout
         uses: actions/checkout@v2
